### ISSUE TITLE
Flash Zip Greyed Out

### ISSUE THREAD

**Issue by iEscapedVim** [axel358/Waydroid-Settings#12]
The Flash zip file to the system image is greyed out ![Screenshot from 2023-02-19 02-57-52](https://user-images.githubusercontent.com/32537564/219901256-08d339dc-6c42-44f2-921b-569e59d518f9.png)

**Comment by axel358** [comment]
This feature has not been implemented yet. It has been removed from the UI in a recent commit to avoid confussion
