### ISSUE TITLE
Made an alternative icon

### ISSUE THREAD

**Issue by Enderteck** [axel358/Waydroid-Settings#17]
I made a quick Icon with inkscape; Feel free to use it and/or set it as the icon for the app <3.

![waydroid-settings](https://github.com/axel358/waydroid-settings/assets/123917079/f83ee556-50ed-47c5-be55-0ac14f21b7b6)

**Comment by Enderteck** [comment]
![waydroid-settings](https://github.com/axel358/waydroid-settings/assets/123917079/7954f6b3-ca64-4764-af70-05d7fa77606f)

**Comment by axel358** [comment]
That looks pretty awesome, but unfortunately we already have an icon

**Comment by Enderteck** [comment]
> That looks pretty awesome, but unfortunately we already have an icon

When I installed the app the .desktop file wasn't using any icons and I don't find one in my files. I don't think it downloaded it.

**Comment by axel358** [comment]
[This is the icon](https://github.com/axel358/waydroid-settings/blob/main/usr/share/icons/hicolor/512x512/apps/cu.axel.WaydroidSettings.png)
If the icon isn't showing in your system try updating the app. If it still doesn't we'll take a look at what could be going on
