### ISSUE TITLE
`Scripts` section is empty

### ISSUE THREAD

**Issue by KAGEYAM4** [axel358/Waydroid-Settings#20]
I have seen other people screenshots where they have many items under `Scripts` section, but for me it is empty.

I got `waydroid-settings` from AUR, i even clean installed it but nothing changed.

![image](https://github.com/axel358/waydroid-settings/assets/75798544/1f84663c-7904-4742-8d65-e304c07dc8c6)

**Comment by electrikjesus** [comment]
You're going to want to use the install instructions in our readme in order to get the scripts synced with the application

**Comment by KAGEYAM4** [comment]
Ok. Thank you.
