### ISSUE TITLE
app can not launch

### ISSUE THREAD

**Issue by aksharlabs** [axel358/Waydroid-Settings#3]
$ /usr/bin/waydroid-settings.sh
/usr/bin/waydroid-settings.sh: ./waydroid-settings.py: /bin/python: bad interpreter: No such file or directory

**Comment by axel358** [comment]
Could you provide details on what distro u're using?

**Comment by aksharlabs** [comment]
I changed starting line with bin/pyrhon to python3  on script then working
ok.
