### ISSUE TITLE
Sudo password dialogs are not sanitizing special characters.

### ISSUE THREAD

**Issue by tekaeren** [axel358/Waydroid-Settings#4]
Using version at commit https://github.com/axel358/Waydroid-Settings/commit/1e67165ff3d21d2e32bbed2e58d7654be02d375c.

When app prompts for user (and not root, as dialog title states) password on start to get sudo priviledges, the value that is entered is not sanitized against use of special characters and fails to authenticate.

Case: user password contains special character: '$', and puts that in sudo prompt at app start.
How it should work: Password is accepted and app starts.
How app behaves: Password is not accepted. Wrong password messages are displayed in both console and GTK prompt.

**Comment by Thesola10** [comment]
Better idea, ditch that dialog entirely and hook into PolicyKit, much _much_ better handling of different security policies, including those without passwords or without sudo.

**Comment by axel358** [comment]
This has been fixed on the latest versions
