### ISSUE TITLE
 scripts/quackdoc_scripts submodule should be bumped

### ISSUE THREAD

**Issue by JamiKettunen** [axel358/Waydroid-Settings#8]
https://github.com/Quackdoc/waydroid-scripts/commit/e4a72f58d5c6361385ad05f0e9cfea3cc399fa28 has been there for about 3 months, I think it's about time to bring it in here.

Cc. @Quackdoc

**Comment by Quackdoc** [comment]
just pushed a minor update to it, but it should be fine to pull the new commit in
