### ISSUE TITLE
Waydroid Settings Can't Launch

### ISSUE THREAD

**Issue by Anifyuli** [axel358/Waydroid-Settings#9]
Hello, Mister.
I found a error from Waydroid Settings in my host show on this screenshot
![image](https://user-images.githubusercontent.com/73734843/210657296-e6c79170-b5e0-44b5-b85e-6a77baf99399.png)

My hardware and host info is :
- Intel core-i3 6006U
- Fedora 37 Workstation Edition
- Nvidia GeForce 920MX + Intel UHD 520
- 12 GB RAM
- 500 GB HDD

Thanks for read my issue and sorry my English

**Comment by axel358** [comment]
Install the following package: webkit2gtk4.0

**Comment by Anifyuli** [comment]
Oh I see. I will try it. Thanks, Mister

**Comment by dustojnikhummer** [comment]
> Oh I see. I will try it. Thanks, Mister

I can confirm installing gir1.2-vte-2.91 and gir1.2-webkit2-4.0 on Kubuntu 22.10 allowed me to run Waydroid Settings
You should add this to install instructions.

**Comment by iEscapedVim** [comment]
on Arch installing webkit2gtk fixed this issue

`sudo pacman -S webkit2gtk`
